### ISSUE TITLE
Self-hosting Materialious on https://materialious.nerdvpn.de - Feedback Thread

### ISSUE THREAD

**Issue by Sommerwiesel** [Materialious/Materialious#161]
Cheers Ward,
me Weidenwiesel (@weidenwiesel:matrix.org) from the Invidious thread on Matrix here.
I just finished self-hosting Materialious on my server and will use this thread to report my findings.

First off, works really great, no major problems this far.
It's a little bit slower in terms of video playback compared to Invidious but I guess that's due to my instance of invidious using an implementation of yt-httpproxy from TeamPiped, which drastically improves all load times for youtube assets (video, img, stream) and currently doesn't seem to work when using Materialious -> Invidious. I will look into fixing this.

But enough chit-chat, here are the problems I found:

1. Trending page (https://materialious.nerdvpn.de/trending) doesn't load at all. Don't really know what's going on, I temporarly enabled logs and there is just nothing. I cannot fully enable the logs in invidious (due to my promise of not logging any visitors on my public instance), so any kind of advice from you where to look would be appreciated. The Popular page works perfectly. Weird, right?

**UPDATE**: Nevermind, the trending page just started working all of a sudden.

2. Enabling DeArrow completely breaks all asset loading. This also happens on your instance so it's probably unrelated to Materialious but a problem in DeArrow. There is an issue on DeArrow talking about problems when it comes to Invidious. It has always been very buggy. Consequently, this is not a bug, more of an FYI.

3. Autoplay and Play next video don't work. Tested on Firefox and fresh, vanilla Chromium. Works on your instance. Any idea?

Again, great frontend, I will now look into optimizing the video load times.

Cheers

**Comment by WardPearce** [comment]
Currently no way to change the default config, but could be useful to add.

When it comes to deArrow, what browser are you using? Chrome?

**Comment by WardPearce** [comment]
Autoplay works, but also needs to be allowed at the browser level. I'll investigate Play next by default

**Comment by WardPearce** [comment]
Also, @Sommerwiesel lmk if you want your instance added the the public instance list. Please make a new issue using the new instance template

**Comment by WardPearce** [comment]
Issues should be fixed as of #163 & #162

**Comment by WardPearce** [comment]
> Hey @WardPearce, a few questions:
> 
>     * Is there a way to change the default materialious config, i.e. change the default color, player settings, sponsorblock categories for new users?

Tracking for this is now in #165, please open individual issues if you encountering anything else. Thank you for helping to make the project better :heart:
