### ISSUE TITLE
[New instance] materialious.nerdvpn.de

### ISSUE THREAD

**Issue by Sommerwiesel** [Materialious/Materialious#166]
### URL

https://materialious.nerdvpn.de/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Ukraine

### Invidious threads

6

### Twice daily IPV6 rotation

- [X] Yes, but see comment below

### Man in the Middle

no

### Additional information

IPv6 rotation is not done twice daily but by performing automated checks to detect blockage from YT. 
The IPv6 rotation is much more reliable this way as it detects the blockage as soon as it happens (max 1min delay) and rotates only when it happens.

**Comment by WardPearce** [comment]
> FYI: The script I use to detect blockage and ipv6rotate: https://paste.mozilla.org/vLZcTOzu

Aah interesting, been working on improving the official smart ipv6 rotator. So might look into adding something official like this.

**Comment by WardPearce** [comment]
> ### URL
> 
> https://materialious.nerdvpn.de/
> ### Mandatory checks
> 
>     * [x]  Instance has a domain name
> 
>     * [x]  Instance is served over HTTPS
> 
>     * [x]  Statistics (`/api/v1/stats`) are enabled
> 
>     * [x]  Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
> 
>     * [x]  Instance has an automatic hourly restart setup of Invidious
> 
>     * [x]  If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
> 
>     * [x]  Instance is not running any kind of analytics
> 
> 
> ### Maintainer chart
> 
>     * [x]  Ensure that my instance is up to date (less than one month old)
> 
>     * [x]  Ensure a proper uptime of my instance (around 90%)
> 
> 
> ### Host country
> 
> Ukraine
> ### Invidious threads
> 
> 6
> ### Twice daily IPV6 rotation
> 
>     * [x]  Yes
> 
> 
> ### Man in the Middle
> 
> no
> ### Additional information
> 
> IPv6 rotation is not done twice daily but by performing automated checks to detect blockage from YT. The IPv6 rotation is much more reliable this way as it detects the blockage as soon as it happens (max 1min delay) and rotates only when it happens.

Uptime can be tracked via https://status.wardpearce.com/status/materialious, after 2 weeks. I'll add your instance 👍

**Comment by WardPearce** [comment]
> @WardPearce Maintenance has ended. They were really quick in fixing it.

Yup was very fast! Have added back monitoring for your instance. Also you'll be happy to hear the most recent PR merged into main should improve load times (might still be building to docker hub tho)

**Comment by WardPearce** [comment]
@Sommerwiesel might be worthwhile implementing https://github.com/WardPearce/Materialious?tab=readme-ov-file#step-4-optional-but-recommended-self-host-ryd-proxy & https://github.com/WardPearce/Materialious?tab=readme-ov-file#step-5-optional-but-recommended-self-host-syncios on your instance. Will be updating the instance list soon to indicate if these options are configured. Is up to you if you want to configure them or not

**Comment by WardPearce** [comment]
> @WardPearce Just took a quick glance and sure. Give me a day or so, I'll ping you when it's done.

Yea no rush, is completely option

**Comment by WardPearce** [comment]
#270 have add your instance, hasn't been 30 days. But considering your an approved instance on Invidious, no harm speeding up the process.
