### ISSUE TITLE
[New instance] https://materialious.einfachzocken.eu

### ISSUE THREAD

**Issue by bugmaschine** [Materialious/Materialious#197]
### URL

https://materialious.einfachzocken.eu

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Invidious threads

6

### Twice daily IPV6 rotation

- [X] Yes

**Comment by WardPearce** [comment]
Thanks for submitting your instance, monitor tracking is done at https://status.wardpearce.com/status/materialious

**Comment by WardPearce** [comment]
@bugmaschine We've updated the issue format for adding new instances, could you please indicate if your instance has configured these optional steps (these steps are completely optional, and don't need to be done to qualify as a public instance)

https://github.com/Materialious/Materialious/blob/main/docs/DOCKER.md#step-4-optional-but-recommended-self-host-ryd-proxy

https://github.com/Materialious/Materialious/blob/main/docs/DOCKER.md#step-5-optional-but-recommended-self-host-syncios

https://github.com/Materialious/Materialious/blob/main/docs/DOCKER.md#step-6-optional-self-host-peerjs

**Comment by bugmaschine** [comment]
@WardPearce My instance currently follows none of these guides, although I may consider updating my instance and will let you know in future

**Comment by ramazansancar** [comment]
I was thinking of adding this. However, I did not add it because I did not know the details. Thanks @bugmaschine

**Comment by bugmaschine** [comment]
What do you mean?

**Comment by ramazansancar** [comment]
I was going to send the project you created as "New instance". Then I saw this. I realized there was no need. Thanks. @bugmaschine

**Comment by bugmaschine** [comment]
@WardPearce I'm shutting down the instance, since our invidious instance no longer works anyways.
