### ISSUE TITLE
Top of window covered by top bar of website

### ISSUE THREAD

**Issue by SwissArmyWrench** [Materialious/Materialious#274]
**Describe the bug**
The top edge of the video's frame is hidden by the bar at the top containing the search bar, hamburger button, settings, etc. It also cuts off the top of the thumbnail of the video on the right in the suggested list.

**To Reproduce**
1. Ensure you are on latest docker image
2. Pull up a video
3. Notice that the top of the frame is hidden.

**Expected behavior**
The full frame of the video is visible and not hidden by the top bar.

**Screenshots**
![image](https://github.com/Materialious/Materialious/assets/137639586/6cb4753a-4af0-40eb-acaa-fc4f47c41cd7)
He is editing a file that's only a few lines long and none of it is visible.

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox
 - Version: Materialious 1.0.4

**Comment by WardPearce** [comment]
Thanks for reporting the bug! Should be fixed as of #275 now.

**Comment by SwissArmyWrench** [comment]
It's better but the top edge is still a bit obscured:
![image](https://github.com/Materialious/Materialious/assets/137639586/6a544a3a-86ad-49a3-8ba7-7a2ca7012e37)

**Comment by WardPearce** [comment]
@SwissArmyWrench Possibly ctrl+shift+r as I can't replicate that locally with any scaling.

**Comment by SwissArmyWrench** [comment]
Yep, all good now. Odd that it was half fixed before that. All good now. Thanks!
