### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [Materialious/Materialious#278]
It seems like all your release APKs identify as

    package: name='us.materialio.app' versionCode='1' versionName='1.0'

Maybe you forgot to version them? [In your `build.gradle` here](https://github.com/Materialious/Materialious/blob/main/materialious/android/app/build.gradle#L10) it currently should rather say something like

```gradle
        versionCode 6
        versionName "1.0.6"
```

* `versionCode 6`: there are already 5 prior releases, so this integer needs to be higher than 5. This is what Android uses internally to tell if an APK provides an update to the already installed version.
* `versionName "1.0.6"`: this is what those using your app will see, so when they e.g. report issues to you they are able to tell what version the issue exists in. Should ideally be in sync with the tag/release name :wink:

May I suggest keeping those updated with each release? Thanks in advance!

**Comment by WardPearce** [comment]
Yea good catch, completely forgot about updating build.gradle

**Comment by WardPearce** [comment]
Fixed now, also added a small script to keep versioning up to date everywhere

https://github.com/Materialious/Materialious/blob/main/update_versions.py

**Comment by IzzySoft** [comment]
Wonderful– and a fresh release available right away! May I offer you to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for your Readme to link to your app's new presence at IzzyOnDroid, [where it will show up](https://apt.izzysoft.de/packages/us.materialio.app/) with the next sync around 6 pm UTC?

![image](https://github.com/Materialious/Materialious/assets/6781438/b392a6cd-4c4d-4013-9ce1-97587a173634)

Should you have some more screenshots to add, I gladly take them. I can also send you a PR with the metadata (description + images) from what is set up here using Fastlane format, so you could use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on it (adding screenshots, featureGraphic, maybe even per-release changelogs) which then would be checked and changes pulled along with each new release you make (those checks happen once per day by default).

**Comment by WardPearce** [comment]
Sounds good, feel free to open a PR 👍

**Comment by IzzySoft** [comment]
There you go :smiley:
