### ISSUE TITLE
Minor UI additions/changes

### ISSUE THREAD

**Issue by Spaghetto392** [Materialious/Materialious#286]
**Is your feature request related to a problem? Please describe.**
Materialious currently has a fairly polished interface, however some features are currently missing that peers like Freetube currently have. To help adoption of Materialious I believe the following UI changes should be considered.

**Describe the solution you'd like**
- Youtube likes should be visible regardless of if Return Youtube Dislikes is enabled.
- Comment threads should be able to be collapsed after expanding.
- An option to view a videos transcript should be available.
- The ability to search Youtube channels videos (maybe a duplicate of #78 ?)
- Video thumbnails should try to maintain their original aspect ratio, as to show the full thumbnail.
- Make the Materialious logo a shortcut to home/subscriptions
- Add an option to hide the trending tab / home (maybe hide home if invidious instance has it disabled?)

**Describe alternatives you've considered**
N/A

**Additional context**
I thought it appropriate to make this a list instead of separate issues as to avoid clutter. If you would rather I split this list out into separate issues, please let me know.

**Comment by Spaghetto392** [comment]
I thought of two more additions that may be considered.

- Add avatars to subscription management tab.
- Add subscription avatars to side panel similar to Freetube or Youtube.

**Comment by WardPearce** [comment]
> I thought of two more additions that may be considered.
> 
>     * Add avatars to subscription management tab.
> 
>     * Add subscription avatars to side panel similar to Freetube or Youtube.

"Add avatars to subscription management tab." is super doable as it would require a request to every channel individually just to get the avatar

**Comment by Spaghetto392** [comment]
@WardPearce Just to clarify, do you mean super doable or undoable? If you meant undo-able, I understand. Perhaps on smaller instances it could work with caching? Thank you.

**Comment by WardPearce** [comment]
> @WardPearce Just to clarify, do you mean super doable or undoable? If you meant undo-able, I understand. Perhaps on smaller instances it could work with caching? Thank you.

*isnt super doable

**Comment by WardPearce** [comment]
And yes "The ability to search Youtube channels videos" is a duplicate of #78

**Comment by WardPearce** [comment]
"videos transcript should be available." will be a somewhat large feature, so should go into a separate issue.

**Comment by Spaghetto392** [comment]
Okay, I'll open a new feature request then.
