### ISSUE TITLE
Materialious Accent Color Changes on Page Refresh

### ISSUE THREAD

**Issue by Spaghetto392** [Materialious/Materialious#291]
**Describe the bug**
When a video is refreshed via browser refresh, the instance's set accent color is ignored and set back to purple.

**To Reproduce**
Open a video, set an accent color, and refresh.

**Expected behavior**
The accent color should stay consistent between refreshes.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Librewolf
 - Version:  1.0.8

**Comment by WardPearce** [comment]
> **Describe the bug** When a video is refreshed via browser refresh, the instance's set accent color is ignored and set back to purple.
> 
> **To Reproduce** Open a video, set an accent color, and refresh.
> 
> **Expected behavior** The accent color should stay consistent between refreshes.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Linux
> 
>     * Browser: Librewolf
> 
>     * Version:  1.0.8

I'm unable to replicate, follow "Open a video, set an accent color, and refresh." will result in my locally set accent color being used.

**Comment by Spaghetto392** [comment]
@WardPearce Hi,

Upon further investigation this is apparently a bug caused by the dark reader extension, which I happened to have installed on accident in my test environment. Given this doesn't seem to be a bug with Materialious itself, I will close the issue. My apologies.
