### ISSUE TITLE
Make channels blacklistable

### ISSUE THREAD

**Issue by Spaghetto392** [Materialious/Materialious#303]
**Is your feature request related to a problem? Please describe.**
Frequently when looking in the recommended feed, I see Youtube channels I have no interest in viewing or are otherwise distracting (all caps, clickbait, etc.) and I would really like a way to blacklist these channels from showing up.

**Describe the solution you'd like**
A way to make channels blacklistable/blocked from appearing in recommended.

**Comment by WardPearce** [comment]
Possibly should be apart of https://github.com/Materialious/api-extended too

**Comment by Spaghetto392** [comment]
Sounds like a good idea.

**Comment by WardPearce** [comment]
nah should be good

**Comment by Spaghetto392** [comment]
Hey, @WardPearce, a bit late, I know, but was this ever implemented? I've been trying to find the relevant commit, but haven't seen it thus far on either this repo, or [api-extended](https://github.com/Materialious/api-extended).

**Comment by WardPearce** [comment]
Hey, currently I'm making this issue out of scope.

**Comment by Spaghetto392** [comment]
Very well, I do hope you consider adding it eventually, as it is probably my biggest issue right now with Youtube frontends. Perhaps it would make more sense for Invidious to implement it though...
