### ISSUE TITLE
Add a decapitalization option for video titles

### ISSUE THREAD

**Issue by Spaghetto392** [Materialious/Materialious#304]
**Is your feature request related to a problem? Please describe.**
On Youtube, a large amount of channels have a habit of using all caps in their titles. This can be very distracting/annoying.

**Describe the solution you'd like**
Implement an automatic system that takes titles such as "ALL CAPS TITLE" and change the capitalization to "All Caps Title"

**Comment by WardPearce** [comment]
> **Is your feature request related to a problem? Please describe.** On Youtube, a large amount of channels have a habit of using all caps in their titles. This can be very distracting/annoying.
> 
> **Describe the solution you'd like** Implement an automatic system that takes titles such as "ALL CAPS TITLE" and change the capitalization to "All Caps Title"

Implemented with version 1.0.11, Can be set to `lowercase`, `uppercase`, `title case` or `sentence case`

**Comment by WardPearce** [comment]
> From my testing, title case doesn't seem to be working correctly. Or perhaps I'm misinterpreting what it does? What I expected it to do was capitalize each word while also making the next letters of the word lowercase, e.g. "HELLO WORLD" to "Hello World". From what I can tell in testing, it does do the first part but not the second.

Must of missed that when testing

**Comment by WardPearce** [comment]
> @WardPearce Out of curiosity, what is the syntax for the option via `VITE_DEFAULT_SETTINGS`? Looking at the commit I assume it's `titleCase` with the options being the above, correct?

will need to document that

**Comment by WardPearce** [comment]
Appears css text transformation isn't good enough for doing this, so will have to do it programmatically
