### ISSUE TITLE
Documentation about recommendations and app settings

### ISSUE THREAD

**Issue by R0GGER** [Materialious/Materialious#307]
While setting up Materialious in Docker several recommendations are made such as;
* RYD-Proxy
* Invidious API extended
* PeerJS

Questions (Docker):
- Why are these apps recommended?
- What do these apps do?

Questions (app settings):
- How to setup Syncious? (Instance URL) And what is Syncious?
- What is DeArrow?

**Comment by R0GGER** [comment]
https://github.com/Materialious/Materialious/pull/346

**Comment by R0GGER** [comment]
It is still unclear to me :confused: what PeerJS is for in Materialious.

**Comment by WardPearce** [comment]
> It is still unclear to me 😕 what PeerJS is for in Materialious.

Sync parties uses peerjs
