### ISSUE TITLE
[feature] material you theming

### ISSUE THREAD

**Issue by theotheroracle** [Materialious/Materialious#308]
**Is your feature request related to a problem? Please describe.**
I really prefer for my UI to be harmonious, and having to put the color in manually isn't really feasible, because I change my wallpaper frequently .

**Describe the solution you'd like**
the app to grab the system colour palette on launch

**Comment by WardPearce** [comment]
Assuming this on Android? Couldn't find a way in Capacitor to pull Material you color preferences sadly

**Comment by theotheroracle** [comment]
https://github.com/ionic-team/capacitor/issues/7484#issuecomment-2129093908 ?

**Comment by WardPearce** [comment]
Yea Capacitor is just a framework for deploying web apps on Android etc. For whatever reason Capacitor doesn't provide methods to pull the material you accent colour. You could write a plugin to add this functionality tho
