### ISSUE TITLE
Parsing HTML timestamps additional formats

### ISSUE THREAD

**Issue by BentiGorlich** [Materialious/Materialious#309]
**Describe the bug**
A video that uses html in their description timestamps like https://youtube.com/watch?v=QU3y6fRd6Ek causes materialious to render chapters like this: `<a href="some link">Actual Name</a>`

**To Reproduce**
1. Open the video on materialious
2. Look at the chapters
4. See weird timestamps

**Expected behavior**
The html should be removed, not escaped

**Screenshots**
![2024-05-17-14-50-18-383](https://github.com/Materialious/Materialious/assets/25664458/5ade7d9f-2a91-449d-8fe0-25a58d2695f8)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version: 125.0.3

**Comment by WardPearce** [comment]
Hey, this is a bug with parsing timestamps in the format `0:05 - 0:10 Some text`
