### ISSUE TITLE
UI change: Align subscribe and like/dislike elements

### ISSUE THREAD

**Issue by Spaghetto392** [Materialious/Materialious#319]
**Is your feature request related to a problem? Please describe.**
Fairly dumb request, but as a minor way to improve the UI, I think the like/dislike counter and subscribe/unsubscribe button should be aligned with each other.

**Describe the solution you'd like**
When the UI allows it, align the subscribe button with the likes/dislikes.

![Screenshot_20240519_230238](https://github.com/Materialious/Materialious/assets/145975180/221cd3e7-0823-4cc1-88eb-5d7c19a231f1)

**Comment by WardPearce** [comment]
Appears this is very resolution specific & seems to be the only solution aside from hiding functionality
