### ISSUE TITLE
Add option to disable/hide Youtube shorts

### ISSUE THREAD

**Issue by Spaghetto392** [Materialious/Materialious#328]
**Is your feature request related to a problem? Please describe.**
I don't have any interest in Youtube shorts, but constantly have them clutter my feed.

**Describe the solution you'd like**
Add an option to separate Youtube shorts into a separate tab. Alternatively, add an option to disable them altogether.

**Comment by Spaenny** [comment]
I just checked, and Invidious does not currently have a method to determine the video type. As a result, filtering videos can only be accomplished through workarounds.

You could technically obtain the height and width of a video preview and not display it if it is in portrait mode. However, this approach has the drawback of requiring all videos to be loaded on page load, and it also results in the removal of regular videos that happen to use portrait mode but are not intended as short videos. Therefore, this approach is not feasible either.

As of now, I don't think it is possible to add an option to disable or hide YouTube Shorts from the feed.

**Comment by WardPearce** [comment]
> I just checked, and Invidious does not currently have a method to determine the video type. As a result, filtering videos can only be accomplished through workarounds.
> 
> You could technically obtain the height and width of a video preview and not display it if it is in portrait mode. However, this approach has the drawback of requiring all videos to be loaded on page load, and it also results in the removal of regular videos that happen to use portrait mode but are not intended as short videos. Therefore, this approach is not feasible either.
> 
> As of now, I don't think it is possible to add an option to disable or hide YouTube Shorts from the feed.

yup exactly this

**Comment by Spaghetto392** [comment]
One way that this could potentially be done is by moving any video that has in the title "#shorts" into a separate tab. Albeit, maybe due to the false positives it could bring, it would make more sense to have this as a video title blacklist feature e.g. block all videos with "WORD" in the title?
