### ISSUE TITLE
Recognise additional Certificate Authorities from the device.

### ISSUE THREAD

**Issue by jmaris** [Materialious/Materialious#337]
**Describe the bug**
I self host invidious on my internal network, and use my own certificate authority to generate SSL certificates.The CA is installed on my android device but Materialous does not detect it, and instead gives SSL errors.
**To Reproduce**
1. Set up Invidious with SSL from your own Certificate Authority.
2. Add root cert to android
3. Launch app, get ssl errors despite other apps working.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WardPearce** [comment]
Greetings, I don't believe this is a Materialious issue & should be asked to Capacitorjs around adding this functionality to their http plugin.

**Comment by WardPearce** [comment]
@jmaris Materialious has moved off using Capacitor's HTTP plugin and we now support enabling insecure certs (sadly we can't base it off device certificates)
