### ISSUE TITLE
[Android] Pop-out player / Picture in Picture (PiP)

### ISSUE THREAD

**Issue by Handrail9** [Materialious/Materialious#356]
**Is your feature request related to a problem? Please describe.**
When I'm watching YT videos on my phone I'm also usually doing something else like scrolling RedLib, Lemmy, or reading E-mails. In it's current state the Android app does not support a pop-out player like NewPipe, LibreTube, GrayJay, or Clipious.

**Describe the solution you'd like**
I would like to have a PiP option like the other video players just mentioned. The reason I want it is because I really like how this project looks, and that it has sync + proxies Return Youtube Dislike. It's be really cool to have it as my primary YT-watching app.

**Describe alternatives you've considered**
n/a

**Additional context**
[Android Developers PiP Explaination](https://developer.android.com/develop/ui/views/picture-in-picture)

**Comment by WardPearce** [comment]
Hopefully should be resolved when porting Android app to using a native player so dash can be supported.

**Comment by WardPearce** [comment]
Closing in favor of #402
