### ISSUE TITLE
Application is sticking a lot 

### ISSUE THREAD

**Issue by Gauravchaubey66** [Materialious/Materialious#364]
**Describe the bug**
Whenever ever I open the application its lagging and if if try to switch to another tab then application didn't response
**To Reproduce**
1. Go to 'Home tab '
2. Click on 'another tab to switch'
3. See error

**Expected behavior**
It should not lag that much its getting stuck 
**Screenshots**
https://github.com/Materialious/Materialious/assets/149640114/52a4ca47-6e89-4837-8eb3-c69f71af4f02

**Desktop (please complete the following information):**
 - OS: [e.g. Android]
 - Version [1.1.1]

**Smartphone (please complete the following information):**
 - Device: [Vivo y72 (global)]
 - OS: [Android 13]

**Additional context**

**Comment by WardPearce** [comment]
Interesting, I have something similar on my Pixel 6 but isn't as drastic. Seems like its something to do with CapacitorJS as using the website on my phone works perfectly fine https://app.materialio.us/

**Comment by Gauravchaubey66** [comment]
> Interesting, I have something similar on my Pixel 6 but isn't as drastic. Seems like its something to do with CapacitorJS as using the website on my phone works perfectly fine https://app.materialio.us/

O I got this app actually this is using that website to show all data in app.
I am getting the same thing in my all browser brave, dolphin and bromite.

**Comment by WardPearce** [comment]
odd

**Comment by WardPearce** [comment]
New release has fixed what I could replicate on a Pixel 6 emulator.
