### ISSUE TITLE
speed up video upload

### ISSUE THREAD

**Issue by senolfndk** [Materialious/Materialious#365]
Videos are loading very slowly, speed up the loading

Edition Windows 11 Pro
Version 23H2
OS build 22635.3790
Experience Windows Feature Experience Pack 1000.22700.1024.0

**Comment by WardPearce** [comment]
Video load times are dependent on the Invidious instance you use.

**Comment by senolfndk** [comment]
hmm ok

**Comment by WardPearce** [comment]
If you are using the default instance, its located in New Zealand. So might be far away from you

**Comment by senolfndk** [comment]
I just noticed one thing, there is no quality option.

**Comment by WardPearce** [comment]
need to enable dash in settings

**Comment by senolfndk** [comment]
ok
