### ISSUE TITLE
[New instance] <materialious.darkness.services>

### ISSUE THREAD

**Issue by blade10101** [Materialious/Materialious#374]
### URL

https://materialious.darkness.services

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United States

### Invidious threads

10

### IPV6 rotation

- [X] Yes

### Man in the Middle

- [X] No

### Optional Materialious configuration

- [X] RYD-Proxy
- [X] Invidious API extended integration
- [X] Self-hosted PeerJS

### Additional information

http://materialious.darknessrdor43qkl2ngwitj72zdavfz2cead4t5ed72bybgauww5lyd.onion/ is the . onion address

**Comment by WardPearce** [comment]
Thank you for your instance submission. Status tracking can be found here https://status.wardpearce.com/status/materialious
