### ISSUE TITLE
api docker fails to start

### ISSUE THREAD

**Issue by sahara101** [Materialious/Materialious#391]
[yt-api_extended-1_logs.txt](https://github.com/user-attachments/files/16115073/yt-api_extended-1_logs.txt)
Hi, 

I am getting errors on starting the api docker, help appreciated. 

Thanks!

**Comment by jmessy919** [comment]
Same here. I followed the documentation to the letter (omitting only Step 6), and I got the same issue. My Invidious instance works perfectly fine as a Docker Container behind my Nginx Reverse Proxy, but my installation of Materialious got held up at the exact same point as yours. Did you ever figure this out, @sahara101?

**Comment by WardPearce** [comment]
Hey, sorry for not responding quicker. Invidious api extended isn't working currently and I've been taking a break from programming so haven't gotten around to fixing it

**Comment by jmessy919** [comment]
That's ok! Thanks for your response. Helps me to know that I didn't screw anything up on my end. All the best to you! 😄

**Comment by WardPearce** [comment]
As of the latest Invidious update, invidious-api-extended appears to be working fine & was unable to replicate any error.
