### ISSUE TITLE
Watch history progress not shown when browsing videos

### ISSUE THREAD

**Issue by Droppisalt** [Materialious/Materialious#398]
When going to the watch history page (left side, or /history), I can see my imported watch history just fine.

However, when searching on Materialious' search page, watched videos don't show the progress bar at the bottom ([this one](https://raw.githubusercontent.com/Materialious/Materialious/main/previews/setting-preview.png)). I've attached two screenshots showing this behaviour. 

I've recently started using Invidious and only finished settings up Materialious today. There's a good chance I just haven't set it up properly.
In Invidious, I can see the progress bar just fine in the search.

![yt-1](https://github.com/Materialious/Materialious/assets/67336980/387755b6-8b7b-4d7b-8e02-59e8b42ce364)

![yt-2](https://github.com/Materialious/Materialious/assets/67336980/e27e9ac5-ef0d-4d50-9e8f-77ad61bfecc6)

**Comment by WardPearce** [comment]
Watch progress on Materialious, currently only show videos watched on Materialious & the progress they are at. Invidious doesn't have a way of storing watch progress, but only if a video has been watched or not

**Comment by ATypescriptEnjoyer** [comment]
My invidious shows watch progress?:

![image](https://github.com/Materialious/Materialious/assets/8694395/b3b5343c-6058-435c-a655-815a3f1a5378)

I believe it comes from this option: 
![image](https://github.com/Materialious/Materialious/assets/8694395/6778a20b-591d-444e-b9dc-42641bd8d2ad)

**Comment by Droppisalt** [comment]
> Watch progress on Materialious, currently only show videos watched on Materialious & the progress they are at. Invidious doesn't have a way of storing watch progress, but only if a video has been watched or not

Ah, yep! Makes 100% sense. Thanks!

**Comment by WardPearce** [comment]
![image](https://github.com/Materialious/Materialious/assets/27844174/3ab74c66-9ad9-4df8-92ad-51ddf50bda1f)

Aaah yea, Invidious' "Save playback position" works the same as Materialious. Its store in local storage, sadly Invidious doesn't make this data accessible via their API.
