### ISSUE TITLE
Sync Party not working

### ISSUE THREAD

**Issue by freddy1301** [Materialious/Materialious#409]
**Describe the bug**
When I click on Start Sync Party nothing happens except the URL changes. I don understand how you are supposed to use it. I copied the URL over to a Tor Browser Windows but there was no synchronisation whatsoever, no matter if logged in or not.

**To Reproduce**
1. Go to '2 People Icon in the upper right corner'
2. Click on 'Start sync party'

**Expected behavior**
I probably should be able to optain a invite Link and manage Users!?

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40
 - Browser: Brave
 - Version 1.67.123

PS: I think the part where you add a reverse proxy for syncious.example.com is missing in the documentation. I copied the config for ryd.example.com and changes the server_name in the nginx config and ran it through certbot.

**Comment by WardPearce** [comment]
Sync party won't work with tor as tor doesn't support WebRTC (to my understanding). Syncious (invidious-api-extended) doesn't require modifying CORs at the reverse proxy level, as Syncious supports modifying CORs.

Sync party will update the dialog after creating a party. If this isn't happening. Please open the browser console and look for any errors after starting Sync party.
