### ISSUE TITLE
DASH qualities not working as expected

### ISSUE THREAD

**Issue by C8opmBM** [Materialious/Materialious#41]
Hey, very nice job, I love the interface.

I got it working but it seems dash is broken. 
In invidious we have Preferred DASH video quality, can you please implement it here as well?
There's no issues in invidious, playing default at 2160p (I have it setup with dash=best quality).
Can you translate it to be same in materialious? As it is, it's set on auto, starting from 360p when dash enabled.

Other than that, its great, I'm loving it!
Thanks!

**Comment by WardPearce** [comment]
Latest image of Materialious saves quality automatically when selected, and will attempt to find the closest quality on other videos.

**Comment by C8opmBM** [comment]
Unfortunately, I do not experience that behaviour. 

New videos always starts at 360p and auto, I need to manually go and pull the slider all the way to the right and it disables auto and plays in 1080p (with dash enabled).
Without, most defaults at 720p, max res.

Also, history does not work at my end.
Thanks.

**Comment by WardPearce** [comment]
Interesting, yea quality appears to be working as expected in dev env, but not in production.

Will need to see network traffic to see why history isn't working for you, but thats a separate issue.

**Comment by C8opmBM** [comment]
Also it can never play 2160p 
If the video has the option, sliding it to the max will blank the page.

**Comment by WardPearce** [comment]
> Also it can never play 2160p If the video has the option, sliding it to the max will blank the page.

2160p works fine for me, might be youtube rate limiting you :shrug:

**Comment by C8opmBM** [comment]
really weird. Tried your instance as well, same.
And my invidious playing the same video at 4k.
Same browser (brave).

Anyway, its a great piece of software, hope it will mature well.
Thanks again.

**Comment by WardPearce** [comment]
![image](https://github.com/WardPearce/Materialious/assets/27844174/6f28586a-521c-4ae2-a365-106392f4d564)
yea odd is working for me on the hosted instance, anyways ill get onto fixing that quality issue

**Comment by WardPearce** [comment]
Appears to be a issue with vidstack. I've implemented everything I can, so once they fix this will be resolved

**Comment by C8opmBM** [comment]
Awesome!

**Comment by WardPearce** [comment]
Isn't Materialious specific so closing.
