### ISSUE TITLE
Ability to change instances

### ISSUE THREAD

**Issue by lbrdt** [Materialious/Materialious#434]
**Is your feature request related to a problem? Please describe.**
Google is reigning down on youtube frontends and depending on one instance is not reliable in the long run. Most invidious instances now have a "This helps protect our community. Learn more" errors. Even the official materialious instance is bugged out.

**Describe the solution you'd like**
It would be nice to be able to switch instances from the settings slider for instances that allow it.

**Describe alternatives you've considered**
Piped has an instance selection option in the settings panel, but the settings panel takes you to a different page and is cumbersome to set

**Additional context**
Ability to input the instance url directly in the settings panel, just like sponsorblock OR a dropdown list of instances pulled from `redirect.invidious.io`

**Comment by WardPearce** [comment]
Isn't possibly due to CORs, Use Mobile app or desktop client if you want this feature
