### ISSUE TITLE
New Logo Suggestion/Proposal

### ISSUE THREAD

**Issue by SecularSteve** [Materialious/Materialious#436]
**Is your feature request related to a problem? Please describe.**
Old logo seems a bit recycled, so I propose something both a bit original and more attractive.

**Describe the solution you'd like**
I made a new logo in Inkscape. I'd like to put it through a vote first before it's implemented. Changes and criticism are welcome, I'm not trying to force it, at least not without making necessary changes if needed.

**Describe alternatives you've considered**
n/a

**Additional context**
Two versions. One with a Shadow, one without.
![MeterialiousS](https://github.com/user-attachments/assets/aa749792-4f80-455f-913d-5fc365c72f20)
![MaterialiousS](https://github.com/user-attachments/assets/1bd8af09-7143-4157-8ca7-af7cfde02459)
![Meterialious](https://github.com/user-attachments/assets/1c46da64-eeaf-4820-ad8d-ff6906bce683)
![Materialious](https://github.com/user-attachments/assets/19b3ee4f-049c-4fbb-9343-240bad97f188)
[Materialious.zip](https://github.com/user-attachments/files/16578183/Materialious.zip)

ZIP contains SVGs and PNGs.

**Comment by WardPearce** [comment]
Hey, thanks for working on this. I'm totally open to having a new logo for Materialious. Personally your current design I don't completely understand what its meant to represent.

**Comment by SecularSteve** [comment]
> Hey, thanks for working on this. I'm totally open to having a new logo for Materialious. Personally your current design I don't completely understand what its meant to represent.

1. You're welcome, and thank you in return.
2. If the original Invidious logo is supposed to be a combo of the "I, N and V" letters, this is supposed to me a makeshift double-play button represented as an "M, T and I" or something.
Seemed approptiate to try something original, distinct from not only the original, but the rest, and at the same time still indicative that it's Invidious.
But that's just what hit me at that same moment. If you have any suggestions of your own to try out, I'm open to implementing them.

**Comment by SecularSteve** [comment]
P.S.
This could also resolve the issue of #392

**Comment by accountadsjds** [comment]
I love the logo design without shadow but it’s leaning very far into the play button theme causing it to feel generic.

**Comment by WardPearce** [comment]
@SecularSteve have implemented your logo, as its a lot better then reusing the Invidious logo with slightly different colours. I'll leave this issue open if anyone has any feedback now that its implemented.
