### ISSUE TITLE
Error: Failed to fetch

### ISSUE THREAD

**Issue by Snake883** [Materialious/Materialious#451]
**Describe the bug**
When opening the web page to my local instance running the docker, the web page reports "Failed to fetch".

**To Reproduce**
1. Start docker container.
2. Got to local hosted home page of Materialious.
3. See error

**Additional context**
Docker container hosted by Unraid.

Maybe I am missing some installation steps?
I simply installed the docker, and hoping for a PnP solution.

**Comment by WardPearce** [comment]
Please follow the docker instruction giving in the docs.
