### ISSUE TITLE
Doesn't work with NPM

### ISSUE THREAD

**Issue by ptichalouf** [Materialious/Materialious#453]
Hello i'm on unraid,

Invidious works great on yattee and many other stuff but when i put the information from the tutorial into nginx proxy manager, invidious going red directly. Could you help me ? 

![Capture d’écran 2024-08-21 à 08 04 10](https://github.com/user-attachments/assets/9295679b-5619-4279-b74f-0d90f8327e78)
![Capture d’écran 2024-08-21 à 08 05 04](https://github.com/user-attachments/assets/5a4a2e37-3ad1-4c25-a71c-03d61a572c33)
![Capture d’écran 2024-08-21 à 08 04 46](https://github.com/user-attachments/assets/400fceec-9abe-4945-a519-acc18795201d)
![Capture d’écran 2024-08-21 à 08 04 40](https://github.com/user-attachments/assets/6c91bd43-fa7c-46b4-8faa-b3cb1a75eb6e)
![Capture d’écran 2024-08-21 à 08 04 33](https://github.com/user-attachments/assets/ae6613e2-db20-45ef-b018-bf23b70c2124)
![Capture d’écran 2024-08-21 à 08 04 18](https://github.com/user-attachments/assets/a1aa263c-5880-4448-8450-88c045159a20)

Thanks for your hard work

**Comment by WardPearce** [comment]
The access control allow origin header must be the URL of your Invidious instance

**Comment by ptichalouf** [comment]
that was the case and i "fix" it with only this 
![Capture d’écran 2024-08-21 à 08 31 14](https://github.com/user-attachments/assets/21bc55b4-c048-47e5-be45-0b06a7ec0593)

if that could help you <3

**Comment by WardPearce** [comment]
inspect the network traffic on Materialious for requests to Invidious & check that Invidious responses with the correct CORS headers

**Comment by ptichalouf** [comment]
so maybe change the doc with only this for NPM 

`    if ($request_method = OPTIONS) {
      return 204;
    }

    proxy_hide_header Access-Control-Allow-Origin;
    add_header Access-Control-Allow-Credentials true;
    add_header Access-Control-Allow-Origin "https://youtube.ptichalouf.xyz" always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, HEAD, PATCH, PUT, DELETE" always;
    add_header Access-Control-Allow-Headers "User-Agent, Authorization, Content-Type" always;
`


the other one doesn't work :)

**Comment by WardPearce** [comment]
whats the difference?

**Comment by ptichalouf** [comment]
> whats the difference?

this part is the problem delete it or maybe fix it ? 

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;

**Comment by WardPearce** [comment]
aaah yea that deffo shouldn't be included at all & not sure why it is as its not in the Nginx example. Must of been a oversight when whoever pushed the PR for NPM documentation.

Good find and thank you.
