### ISSUE TITLE
Proxy static content from ggpht

### ISSUE THREAD

**Issue by TheSainEyereg** [Materialious/Materialious#457]
**Is your feature request related to a problem? Please describe.**
Well... In my country clown ass government not only [slowing down googlevideo.com because of the "anti-Russian policy" 🤡](https://t.me/Hinshtein/7276) but also [blocked entire yt3.ggpht.com back in 2022](https://reestr.rublacklist.net/en/record/4285828/) . So when I saw no avatars loaded it was obvious to me that Materialious doesn't proxy static at all. Man, why? Even Invidious passes ggpht content through by default.

**Describe the solution you'd like**
Ability to proxy not only video content but also static resources, like It done in Invidious by default

**Describe alternatives you've considered**
Use VPN or other anti-censorship solutions which is not good

**Additional context**
<img src="https://github.com/user-attachments/assets/794d45c6-f745-477c-85af-bfb5b2d2a453" width="400">
<img src="https://github.com/user-attachments/assets/7489f23a-a600-4875-ae91-9418838b988e" width="400">

Btw this is how YouTube in Russia looks like:
<img src="https://github.com/user-attachments/assets/e0f8b22f-8c3d-4b21-b9ec-c58a6472c7ec" width="400">
<img src="https://github.com/user-attachments/assets/c37077c6-4568-4603-af69-2f0c06fde5d5" width="400">

**Comment by Vazgen005** [comment]
![image](https://github.com/user-attachments/assets/0c1f6f06-cb71-4fcc-94ad-bab138193ed4)

**Comment by WardPearce** [comment]
> ![image](https://private-user-images.githubusercontent.com/70487205/361264268-0c1f6f06-cb71-4fcc-94ad-bab138193ed4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Mjg4NzEsIm5iZiI6MTcyNDYyODU3MSwicGF0aCI6Ii83MDQ4NzIwNS8zNjEyNjQyNjgtMGMxZjZmMDYtY2I3MS00ZmNjLTk0YWQtYmFiMTM4MTkzZWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDIzMjkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwODc3YjhkYmY5YTI3OGUwNjQyZjE3YzIwMTA1ZjZkMTIyMjJmNDUyZTU4M2YxMjI3NmI5OWRjNjE2ODI2ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O6ks-rgmSDpuF9b2Q6_LIlP228ncbuFUUQol7pd6DNE)

Good catch, should be fixed once #466 is merged
