### ISSUE TITLE
Default settings are not applying

### ISSUE THREAD

**Issue by TheSainEyereg** [Materialious/Materialious#464]
**Describe the bug**
Materialious makes it possible to set default settings for all users via VITE_DEFAULT_SETTINGS, but after reloading the page somehow all these settings are reset. This is not visually noticeable, because all the switches in the Settings panel remain in their default positions.

On my instance, default settings set up like here:
```yaml
VITE_DEFAULT_SETTINGS: '{ "region": "RU", "proxyVideos": true, "dashEnabled": true, "returnYtDislikes": true, "deArrowEnabled": false }'
```
So I'm going to describe my problem for the most obvious things: RYD and DASH quality

**To Reproduce**
1. In VITE_DEFAULT_SETTINGS set dashEnabled and returnYtDislikes to true 
2. Reload the instance for the changes to take effect
2.o. Clear the Cloudflare cache and so on if there is anything that may have retained the old settings
3. Open a new incognito window in your browser
4. Play any video
5. Either immediately or after reloading the page you will see that there are no RYD or DASH settings.
6. Open the settings sidebar
7. DASH and RYD are enabled as specified in VITE_DEFAULT_SETTINGS :/

**Expected behavior**
I can see dislike count as a DASH settings in Playback player section if all these were enabled by instance owner in VITE_DEFAULT_SETTINGS 

**Screenshots**
![image](https://github.com/user-attachments/assets/dace3f02-6862-45ec-841b-3797d8a25e76)

**Desktop (please complete the following information):**
- OS: any (tested on Windows 11 & Arch Linux)
- Browser Chrome 128.0.6613.84 (Official Build) (64-bit) (cohort: M128 Rollout)
- Version 1.1.7

**Comment by WardPearce** [comment]
Should be fixed via #465, please note setting overwrites are only applied on the 1st time Materialious is loaded for a browser
