### ISSUE TITLE
Add an option to proxy videos

### ISSUE THREAD

**Issue by ralencode** [Materialious/Materialious#520]
**Is your feature request related to a problem? Please describe.**
for me, the main point in using invidious is it's proxying capabilities. youtube is blocked in my country, and i can only watch it through proxy. tho its not hard to bypass the block, id brefer to tick a switch "Proxy videos" in the app's settings

**Describe the solution you'd like**
add a switch "Proxy videos" to the settings

**Describe alternatives you've considered**
proxy by default or use invidious instance's setting (which is not that convinient)

**Comment by WardPearce** [comment]
Proxying videos is in settings

**Comment by WardPearce** [comment]
@ralencode if this is on Android, then dash / proxying isn't a option due to #402

**Comment by ralencode** [comment]
yes, thats about android, and thats why i couldnt find the option in settings

**Comment by WardPearce** [comment]
Yea Materialious is primarily a web app and desktop app, rn Android is somewhat experimental due to COR limitation

**Comment by WardPearce** [comment]
@ralencode, Materialious on Android now supports dash & proxying.
