### ISSUE TITLE
Reinstalling the app breaks it

### ISSUE THREAD

**Issue by ralencode** [Materialious/Materialious#521]
**Describe the bug**
when i reinstall the app, it has no content when opening

**To Reproduce**
1. Go to fdroid
2. Click on install materialious
3. Open materialious
4. It works
5. Return to fdroid
6. Click on uninstall materialious
7. Click on install materialious
8. Open materialious
9. Its blank

**Expected behavior**
the app should be working when i uninstall and install it back

**Screenshots**
https://github.com/user-attachments/assets/05d9d876-9415-4df2-9e24-330dd13b3d8e

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy Note 10]
 - OS: [latest LeafOS 3.2 with Android 14]
 - Browser [firefox, but i used the app]
 - Version [1.2.2]

**Additional context**
i tried clearing cache, data and rebooting, didn't help

**Comment by WardPearce** [comment]
Interesting, unable to replicate using Obtainium. Possibly try restarting your phone and see if it fixes it or might be a weird issue with fdroid distribution
