### ISSUE TITLE
Session expiry

### ISSUE THREAD

**Issue by Sommerwiesel** [Materialious/Materialious#524]
_The bug is related to my own self-hosted instance https://materialious.nerdvpn.de_

**Describe the bug**
Session (log in via my own invidious instance) seems to expire soon. I would really like a login session to presist for at least one day or so.

**To Reproduce**
1. Go to https://materialious.nerdvpn.de
2. Click on login
3. Grant token
4. Get logged in
5. Get logged out after a while or after browser restart

**Expected behavior**
Session expiry be longer

**Desktop (please complete the following information):**
 - OS: Arch Linux Kernel 6.9
 - Browser: Firefox ESR
 - Version: 115.15.0esr

**Additional context**
Maybe a bug on my instance only

**Comment by WardPearce** [comment]
> @WardPearce You're right, Invidious doesn't revoke tokens. It's just that Materialious seems to forget the token it was granted or doesn't re-use it. For my user, there are about a hundred tokens in the DB now, most of them were probably created for use in Materialious. Maybe it's the local storage or maybe it's something with my instance. I stopped being a web dev 10 years ago so I don't really know how to debug this. Do you know how to check where the problem is?

Is fetching notifications failing on Materialious? Because if that fails Materialious deletes auth tokens
