### ISSUE TITLE
Dash Quality always ends up at 144p

### ISSUE THREAD

**Issue by Bobettemcnugget** [Materialious/Materialious#534]
**Describe the bug**
When I activate the "auto" quality toggle, the video quality will never exceed 144p.

If a new video starts, it will be at 144p. If I toggle the switch *while* playing a video at 1080p, it will eventually lower down to 144p even though 1080p was working just fine.

Disabling auto allows me to exceed 144p, however, this setting will not persist, a new videos/sessions will be at the lowest quality settings, require manual intervention every time.

This does not occur on the invidious instance on which materialious connects, videos upgrade fine to the highest quality possible.

**To Reproduce**
1. Watch a video on materialious
2. Set the player quality to "auto"
3. Watch the video quality downgrade 

**Expected behavior**
I expect auto quality to select the highest quality available OR for my manual quality settings to be remembered.

**Desktop (please complete the following information):**
 - OS: Tested on MacOS Sonoma and Windows 11
 - Browser Tested on Brave and Firefox
 - Version Latest

**Additional context**
I know similar issues have been reported in the past, but the real kicker for me is how the video actually downgrades while being watched. How is the need for a downgrade being evaluated? Is it too strict? Inversely, is the player being too strict when considering to upgrade to a better quality level when they are available and so remains at lower qualities? Can any of those settings be changed? By the user?

**Comment by WardPearce** [comment]
I'll leave this issue open here for tracking. But this is to do with vidstack (Our player component)

Please open a issue on their repo here

https://github.com/vidstack/player

**Comment by Bobettemcnugget** [comment]
I added some context in the vidstack bug I've opened as you requested, however I do have some questions as I'm really unfamiliar with this whole stack. Assuming I'm reading this properly: https://www.vidstack.io/docs/player/api/providers/dash

It sounds like you may be able to pass settings to dashjs. Based on this issue I found, which seems to match with my issue:

https://github.com/Dash-Industry-Forum/dash.js/issues/4288

It sounds like tweaking of the ABR settings might be in order, until Dash v5 hits, which includes a refactor of this whole bit. Is my understanding correct or are we relying entirely on vidstack for this?

Cheers!

**Comment by WardPearce** [comment]
> I added some context in the vidstack bug I've opened as you requested, however I do have some questions as I'm really unfamiliar with this whole stack. Assuming I'm reading this properly: https://www.vidstack.io/docs/player/api/providers/dash
> 
> It sounds like you may be able to pass settings to dashjs. Based on this issue I found, which seems to match with my issue:
> 
> [Dash-Industry-Forum/dash.js#4288](https://github.com/Dash-Industry-Forum/dash.js/issues/4288)
> 
> It sounds like tweaking of the ABR settings might be in order, until Dash v5 hits, which includes a refactor of this whole bit. Is my understanding correct or are we relying entirely on vidstack for this?
> 
> Cheers!
> 
> Edit: I may as well link to the dashjs issue regarding the refactoring of ABR: [Dash-Industry-Forum/dash.js#4255](https://github.com/Dash-Industry-Forum/dash.js/issues/4255)

Good fine, I'll experiment with ABR settings

**Comment by WardPearce** [comment]
Latest PR changes ABR mode, in my testing this didn't really fix the auto issue. But I've added a patch so dash will start at whatever quality you select correctly and also changing quality will happening instantly now too.

**Comment by Bobettemcnugget** [comment]
Hello,

As you mentioned, auto is still starting at a poor quality. However, it does look like quality is now being correctly remembered now, and the experience is MUCH improved for it.

Thank you!

**Comment by WardPearce** [comment]
> Hello,
> 
> As you mentioned, auto is still starting at a poor quality. However, it does look like quality is now being correctly remembered now, and the experience is MUCH improved for it.
> 
> Thank you!

Yea fixing the auto detection quality would require me to rewrite the whole system that relies on, what their isnt much point to do as v5 is being worked on. But yea thankfully forcing the quality to stay higher when adjusted was somewhat of a simple patch.
