### ISSUE TITLE
Speed up channel logo load times

### ISSUE THREAD

**Issue by Bobettemcnugget** [Materialious/Materialious#537]
**Describe the bug**

When loading a page on materialious, some channel logos take an inordinate amount of time to load. This is seemingly worse when you have multiple duplicate logos.

As you can see in the screenshot below, all logos load in a random order, which can be a jarring experience. Some of them may never load.

**Expected behavior**
I expect all logos to load reasonable quickly and simultaneously

**Screenshots**
<img width="1125" alt="Screenshot 2024-09-15 at 07 54 28" src="https://github.com/user-attachments/assets/0e92955b-0c4e-4fe9-afb9-88c3fdb96d13">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Browser  Brave
 - Version Latest

**Additional context**
One thing I've noticed is that this is seemingly worse when the same channel appears multiple times within a page. Looking at the developper console, it looks like a new/different request is being made for the same logo multiple times during a page load. I feel this could probably be optimized (i.e: download the same image only once).

The console shows that the vast majority of logos load within 1ms, however some of them take >20ms and appear to be stalled/queued. This may be a result of the multiple requests being made for the same image repeatedly. My quick napkin math shows about 20-30% of the requests for logos end up stalled and delayed by 20 ms or more compared to the rest.
<img width="339" alt="Screenshot 2024-09-15 at 08 00 00" src="https://github.com/user-attachments/assets/1e9831a4-dd9f-4598-bedf-8d3dd3f8c802">

**Comment by WardPearce** [comment]
Lower author thumbnail quality in latest PR, thank you.

**Comment by Bobettemcnugget** [comment]
While this will surely improve things for people connecting to remote instance, this unfortunately doesn't fix the problem I am seeing here.

In the second screenshot in my original message, you can see the actual content download time is negligible. In my case, materialious is running on the same box as invidious, so file size is not a bottleneck.

As you can see, it spends the large majority of the request stalling. This appears to be due to a limitation of chromium based browsers: https://developer.chrome.com/docs/devtools/network/reference/?utm_source=devtools#timing-explanation

Whereas only a certain amount of tcp connections is allowed at once to a given origin. This is also true with Firefox, however that limit is doubled.

There's two ways I imagine this could potentially be solved:

1. Reduce the amount of connections required to avoid queuing. I believe in this case the core problem is that we are redownloading the same image multiple times. To be precise, say if my page has a lot of videos coming from CBC, it will initiate a single request every time the CBC logo is displayed, to a different URL. Given a user has a big chance of seeing the same image multiple time on their subscription page, this is bound to happen often. Ideally, the same image should only be requested once.
2. Probably some caching, but would likely mean solving 1 anyways.

Thanks again for being really reactive, this is a really cool project!

**Comment by WardPearce** [comment]
> While this will surely improve things for people connecting to remote instance, this unfortunately doesn't fix the problem I am seeing here.
> 
> In the second screenshot in my original message, you can see the actual content download time is negligible. In my case, materialious is running on the same box as invidious, so file size is not a bottleneck.
> 
> As you can see, it spends the large majority of the request stalling. This appears to be due to a limitation of chromium based browsers: https://developer.chrome.com/docs/devtools/network/reference/?utm_source=devtools#timing-explanation
> 
> Whereas only a certain amount of tcp connections is allowed at once to a given origin. This is also true with Firefox, however that limit is doubled.
> 
> There's two ways I imagine this could potentially be solved:
> 
>     1. Reduce the amount of connections required to avoid queuing. I believe in this case the core problem is that we are redownloading the same image multiple times. To be precise, say if my page has a lot of videos coming from CBC, it will initiate a single request every time the CBC logo is displayed, to a different URL. Given a user has a big chance of seeing the same image multiple time on their subscription page, this is bound to happen often. Ideally, the same image should only be requested once.
> 
>     2. Probably some caching, but would likely mean solving 1 anyways.
> 
> 
> Thanks again for being really reactive, this is a really cool project!

aaah yea, this is a issue caused with Materialious using fetch to load avatars due to limitations brought in by the new download feature adding 
```Cross-Origin-Opener-Policy "same-origin"
  Cross-Origin-Embedder-Policy "require-corp"```
  
 and some Invidious avatars are missing the correct response header, will have to look into adding some sort of cache manually.

**Comment by WardPearce** [comment]
Have gone back to loading images using the image tag, what handles catching. Will work on #542 so less requests are queued too
