### ISSUE TITLE
Videos fail to load

### ISSUE THREAD

**Issue by SleuthChromiumUser** [Materialious/Materialious#568]
I can't play any videos. Error encountered.

**Comment by WardPearce** [comment]
https://github.com/iv-org/invidious/issues/4734

Try using the latest version of Materialious, what has a fallback feature what may or may not work depending if YouTube has blocked you

**Comment by SleuthChromiumUser** [comment]
Oh ok. I am using the latest version on F-Droid, but maybe the F-Droid version is behind. I'll check the Github page.



________________________________
