### ISSUE TITLE
[Feature Request] An option for setting default DASH quality, like `quality_dash` in Invidious

### ISSUE THREAD

**Issue by engels74** [Materialious/Materialious#592]
Hey!
First off, thanks for making this beautiful front-end for Invidious.

**Is your feature request related to a problem? Please describe.**
I’m using Materialious and I noticed that it seemingly lacks the `quality_dash` option. In Invidious, this option allows setting a default quality for DASH streams, which is useful for having the default quality already set, before clicking on a video. 

Currently, I can't seem to find an option for setting a default quality when using DASH streams in Materialious, which is a feature I  rely on when otherwise using Invidious. Not having the quality_dash in Materialious makes managing video quality more cumbersome, especially when switching between different videos or devices.

**Describe the solution you'd like**
I would like Materialious to implement the `quality_dash` option, similar to the way it is available in Invidious. This would allow users to specify a default DASH quality (e.g., auto, best, 1080p, 720p) in the settings. It would provide more control over the video experience, enabling users to fine-tune their viewing preferences directly within Materialious.

**Describe alternatives you've considered**
An alternative would be to revert to using Invidious directly, but this defeats the purpose of using Materialious as a front-end for its nicer looking interface.

**Additional context**
In Invidious, the configuration options are as follows:
```
  ##
  ## Default dash video quality.
  ##
  ## Note: this setting only takes effet if the
  ## 'quality' parameter is set to "dash".
  ##
  ## Accepted values:
  ##    auto, best, 4320p, 2160p, 1440p, 1080p,
  ##    720p, 480p, 360p, 240p, 144p, worst
  ## Default: auto
  ##
  #quality_dash: auto
```

Kind regards,
engels74

**Comment by WardPearce** [comment]
Currently Materialious does save what quality you set on a video & tries to match it to similar qualities on other videos you watch.

**Comment by engels74** [comment]
> or is this being able to set a default quality on a Materialious instance?

Yes, sorry if I wasn't making that clear :). I'm the one hosting an instance and would like to be able to set the default dash quality like I can in Invidious :)

**Comment by WardPearce** [comment]
aah okay, I'll had a default bitrate value in the next update 👍

**Comment by engels74** [comment]
> aah okay, I'll add a default bitrate value in the next update 👍

Awesome, thank you ❤️

**Comment by WardPearce** [comment]
This has been added in the most recent update with `VITE_DEFAULT_DASH_BITRATE`, please note this will only apply to users who haven't set their video quality. Once a user changes video quality this no longer applies.

**Comment by engels74** [comment]
> This has been added in the most recent update with `VITE_DEFAULT_DASH_BITRATE`, please note this will only apply to users who haven't set their video quality. Once a user changes video quality this no longer applies.

That was quick! Thanks!

Would it be too hard / cumbersome to use the same "settings" as Invidious has? The: 
```
  ## Accepted values:
  ##    auto, best, 4320p, 2160p, 1440p, 1080p,
  ##    720p, 480p, 360p, 240p, 144p, worst
  ## Default: auto
```

The `999999` option serves me well, but it's hard to figure out what value e.g. 1080p is at :)

**Comment by WardPearce** [comment]
Yea dashjs only takes bitrate, so I'd have to add extra logic to workout what resolution equals what bitrate, what personally i think just leaves you with less control.

**Comment by engels74** [comment]
> Yea dashjs only takes bitrate, so I'd have to add extra logic to workout what resolution equals what bitrate, what personally i think just leaves you with less control.

Would it be possible to have both? :). Like both being able to _either_ use the bitrate value (as it is now) and the auto/best/1080p/720p and so on (or whatever logic you could implement). That would be awesome. 

But I understand if that would be too much work

**Comment by WardPearce** [comment]
haha ye i am lazy, if someone else requests it I'll add it or if i get some spare time
