### ISSUE TITLE
Reduce image size on your homepage

### ISSUE THREAD

**Issue by melroy89** [Materialious/Materialious#606]
**Is your feature request related to a problem? Please describe.**

Please consider reducing the image on your homepage: https://materialio.us/

The image on your homepage is a massive 3.50 MB! Come on. This image can be easily reduced to around 100kb.

**Describe the solution you'd like**

Reduce resolution and use webp.

**Additional context**

When loading this page from EU, the image is slowing too slowly. Think about the user experience.

**Comment by melroy89** [comment]
Also better configure your Nginx server.. I can see the version number on the headers: nginx/1.27.1. Use `server_tokens   off;`! See more production configs at: https://gitlab.melroy.org/-/snippets/87

**Comment by WardPearce** [comment]
Please open this issue here

https://github.com/Materialious/Landing

**Comment by melroy89** [comment]
Issue created & PR created: https://github.com/Materialious/Landing/pull/2
