### ISSUE TITLE
I encountered an error

### ISSUE THREAD

**Issue by LordDarksflame** [Materialious/Materialious#607]
Hello there I had problems anytime I put materialious.nadeko.net in higher video pixels it give me a error message or the videos won't play at all
![Screenshot_20240926_232530_Edge](https://github.com/user-attachments/assets/aa99deee-845c-4954-83fb-2b4cb2017226)

**Comment by WardPearce** [comment]
https://github.com/iv-org/invidious/issues/4734

Desktop & Android app provide local fallback
