### ISSUE TITLE
Improve link previews

### ISSUE THREAD

**Issue by Bobettemcnugget** [Materialious/Materialious#618]
I have a small instance I share with a few friends. We often share links over Discord however I've noticed the link preview is quite generic:

<img width="295" alt="Screenshot 2024-10-01 at 19 55 54" src="https://github.com/user-attachments/assets/060801a0-0dd3-42c2-a195-6e3dced4f472">

When linking through invidious we get a proper preview:
<img width="545" alt="Screenshot 2024-10-01 at 19 56 46" src="https://github.com/user-attachments/assets/f0d88fb6-e540-4968-a236-e6ac2a19db31">

I think it would be more engaging for Materialious links shared through social media to have proper link previews to inform the user of the contents of the link.

Cheers!

**Comment by Bobettemcnugget** [comment]
OpenGraph seems like a pretty standard way to implement this that is supported by most platforms: https://ogp.me/

**Comment by Bobettemcnugget** [comment]
That seems to be how Invidious implemented it:

https://github.com/iv-org/invidious/blob/53e8a5d62d4d7d66e8819f221a1c7b168102995c/src/invidious/views/channel.ecr#L30

https://github.com/iv-org/invidious/blob/53e8a5d62d4d7d66e8819f221a1c7b168102995c/src/invidious/views/watch.ecr#L10

**Comment by WardPearce** [comment]
Isn't possible with Materialious due to being a serverless SPA

**Comment by WardPearce** [comment]
Materialious is built with sveltekit as a spa, dynamic metadata Isn't possible without a server.
