### ISSUE TITLE
question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [Materialious/Materialious#621]
The updater at IzzyOnDroid alerted us about some sensible permissions requested by the app:

```
! repo/us.materialio.app_45.apk declares sensitive permission(s):
  android.permission.READ_MEDIA_IMAGES android.permission.CAMERA
```

Could you please clarify what those are needed for? Thanks in advance!

**Comment by WardPearce** [comment]
Thanks for the issue, I'll need to investigate this because I'm not exactly sure why its requesting those permission. We don't directly ask for them in our manifest file, possibly a plugin we use is requiring them.

**Comment by IzzySoft** [comment]
Thanks! Best luck then to find the culprit! In the worst case, if you're sure they're not needed but cannot figure what drags it in, there's always the option of [Removing Unwanted Manifest Permissions With tools:node](https://developermemos.com/posts/removing-unwanted-manifest-permissions/) :wink:

Btw, I forgot to copy over one line from the "alert":

```
! repo/us.materialio.app_46.apk declares flag(s): usesCleartextTraffic
```

What for is unencrypted traffic needed by the app, and where to?

**Comment by WardPearce** [comment]
> Thanks! Best luck then to find the culprit! In the worst case, if you're sure they're not needed but cannot figure what drags it in, there's always the option of [Removing Unwanted Manifest Permissions With tools:node](https://developermemos.com/posts/removing-unwanted-manifest-permissions/) 😉
> 
> Btw, I forgot to copy over one line from the "alert":
> 
> ```
> ! repo/us.materialio.app_46.apk declares flag(s): usesCleartextTraffic
> ```
> 
> What for is unencrypted traffic needed by the app, and where to?

Materialious requires unencrypted traffic due to how we bypass CORS using `cors-anywhere` what runs locally within the Android app using android nodejs. We have to bypass CORS like this due to being a Capacitorjs app & their HTTP patch doesn't work with dashjs

**Comment by WardPearce** [comment]
Materialious 1.6.2 has removed `CAMERA` & `READ_MEDIA_IMAGES` from permissions, thank you for reporting this.

**Comment by IzzySoft** [comment]
Thanks! Confirmed :smiley: `usesCleartextTraffic` was added to the app's "green list" with your explanation, and thus will no longer throw any warnings here either.
