### ISSUE TITLE
Split the Video into chapters/segments established in the description

### ISSUE THREAD

**Issue by SecularSteve** [Materialious/Materialious#657]
**Is your feature request related to a problem? Please describe.**
The videos still have no feature in Materialious where they're split off into separate segments/chapters if they're specified by timeframes in the description.

**Describe the solution you'd like**
For that feature to simply be implemented. Would make knowing where in the video I need to go much easier.

**Describe alternatives you've considered**
Not sure if there could be any. Seems like a must-have feature for any client these days. If it's possible at all that is.

**Additional context**
Two screenshots taken of the same video on my Android in fullscreen. One from YT Regular, the other from Materialious.
it speaks for itself that the YT one has the video obviously split into segments.

![Screenshot_2024-10-21_13-38-30](https://github.com/user-attachments/assets/52cf2442-847e-43b5-81e3-f869c78edc58)
![Screenshot_2024-10-21_13-39-12](https://github.com/user-attachments/assets/ac99fcfd-4e73-445e-8aaa-94661d94373c)

**Comment by WardPearce** [comment]
Greetings, Materialious does indeed have this feature but currently isn't in use for the YouTubejs fallback used on the Desktop & Android app. Will be resloved when #656 is closed.

If this isn't to do with the local video fallback, please reopen this issue.
