### ISSUE TITLE
Fullscreen won't automatically rotate to the desired side

### ISSUE THREAD

**Issue by SecularSteve** [Materialious/Materialious#671]
**Is your feature request related to a problem? Please describe.**
Whenever I go fullscreen, it's always rotated rightside down. 
It won't do much as flip itself to leftside down when I turn the phone upside down.

**Describe the solution you'd like**
Pictures below related.

**Describe alternatives you've considered**
Not sure if there could be any other than a different client.

**Additional context**
Only fullscreen mode allowed:
![Screenshot_2024-10-25_00-07-37.png](https://github.com/user-attachments/assets/9b96cde7-cbb0-4e92-8858-7c08e565a243)

What I expect: 
![Screenshot_2024-10-25_00-08-14.png](https://github.com/user-attachments/assets/271decd0-0abd-4a7c-9d6a-c493d1f71efb)
![Screenshot_2024-10-25_00-08-18.png](https://github.com/user-attachments/assets/c8730d0e-cd1d-4d54-af33-74e6809820d7)
![Screenshot_2024-10-25_00-08-53.png](https://github.com/user-attachments/assets/195df537-2004-446d-8cb6-ea6dbd53b3a6)

**Comment by WardPearce** [comment]
> **Is your feature request related to a problem? Please describe.** Whenever I go fullscreen, it's always rotated rightside down. It won't do much as flip itself to leftside down when I turn the phone upside down.
> 
> **Describe the solution you'd like** Pictures below related.
> 
> **Describe alternatives you've considered** Not sure if there could be any other than a different client.
> 
> **Additional context** Only fullscreen mode allowed: ![Screenshot_2024-10-25_00-07-37.png](https://private-user-images.githubusercontent.com/33793273/379950880-9b96cde7-cbb0-4e92-8858-7c08e565a243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzE3ODAsIm5iZiI6MTcyOTgzMTQ4MCwicGF0aCI6Ii8zMzc5MzI3My8zNzk5NTA4ODAtOWI5NmNkZTctY2JiMC00ZTkyLTg4NTgtN2MwOGU1NjVhMjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA0NDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYWZlMGJkMzM0OTYyM2ViNWNiNmY5MzUzNDllYTc3YTBjNjU5MDcyZGY5YzcwYmJkYmY1NTE5NWI1N2EzMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7bGCjl9_dev10N2WuqjwAR1uQSNN170DWAOJmY9ewCo)
> 
> What I expect: ![Screenshot_2024-10-25_00-08-14.png](https://private-user-images.githubusercontent.com/33793273/379950936-271decd0-0abd-4a7c-9d6a-c493d1f71efb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzE3ODAsIm5iZiI6MTcyOTgzMTQ4MCwicGF0aCI6Ii8zMzc5MzI3My8zNzk5NTA5MzYtMjcxZGVjZDAtMGFiZC00YTdjLTlkNmEtYzQ5M2QxZjcxZWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA0NDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDQyNmViYTljM2E2MTZhYzVkNjlkODEzNjhkNDI2OGUxNjBjZWY3NDNiZTRjMzgzNzZkOGM5YjIwOTMzZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y4sCHmLT-PFL6Qo_iz6g0Ob5IO5QU6XFUbNV2lzoAMg) ![Screenshot_2024-10-25_00-08-18.png](https://private-user-images.githubusercontent.com/33793273/379950945-c8730d0e-cd1d-4d54-af33-74e6809820d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzE3ODAsIm5iZiI6MTcyOTgzMTQ4MCwicGF0aCI6Ii8zMzc5MzI3My8zNzk5NTA5NDUtYzg3MzBkMGUtY2QxZC00ZDU0LWFmMzMtNzRlNjgwOTgyMGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA0NDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZDk0YzJhNWJlM2E0MjgwZDU4NmI0NjRkN2EwMGZjMzA2OGFhN2Y5MTQ0NDA0YTk3Y2I4NGY1OTNmZjMwNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wj4gl_R-V79GwECrCf54IAx1C9Fh6wolDJNuxSjCY-I) ![Screenshot_2024-10-25_00-08-53.png](https://private-user-images.githubusercontent.com/33793273/379950958-195df537-2004-446d-8cb6-ea6dbd53b3a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzE3ODAsIm5iZiI6MTcyOTgzMTQ4MCwicGF0aCI6Ii8zMzc5MzI3My8zNzk5NTA5NTgtMTk1ZGY1MzctMjAwNC00NDZkLThjYjYtZWE2ZGJkNTNiM2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA0NDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNGMzZjQ4MGQ3NzNlMjcxYjMxYmIzMGMxM2Y2ODI0MTRjMDdmY2M1NWVmZjkyY2ZkMDMxMjc0Nzg2ZDRlMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mNOqK2M0xs9b4TSAAubSI9bMSWLHMXO-vXkQ_AeY7v8)

Disable lock aspect ratio in player settings to allow all rotations. But I agree with this setting enabled should allow you to rotate landscape in both directions

**Comment by SecularSteve** [comment]
That fixed it, though I'd personally just have the option either set to off by default for new users, or have the "lock screen" function as an icon somewhere on the player screen instead.

But that's just my suggestion.

**Comment by WardPearce** [comment]
Doesn't appear to be a solution using Capacitors native plugin for setting screen orientation for landscape to support both directions for whatever reason.
