### ISSUE TITLE
"This video may be inappropriate for some users."

### ISSUE THREAD

**Issue by l0acl** [Materialious/Materialious#681]
Suggestion: Add a way to view those videos or add a way to connect your email to "Materialious" (I enjoy the experience overall but I think the suggestion will make it better, keep up the good work.)

**Comment by Spaghetto392** [comment]
This is an issue with Invidious, you may find the relevant issue [here](https://github.com/iv-org/invidious/issues/2189). There is currently nothing that can be done.
