### ISSUE TITLE
Requested resolution is ignored upon first load/seemingly at random

### ISSUE THREAD

**Issue by Spaghetto392** [Materialious/Materialious#697]
**Describe the bug**
Upon first loading the page and starting video playback with DASH enabled, the requested resolution is often ignored and seems to remain on auto. This seems to also happen at random when loading a new video. Changing the resolution settings via the player UI does not affect the resolution while this bug is in effect.

**To Reproduce**
Start a new browser session (no cookie data, etc.) load chosen instance of Materialious and if not enabled, enable DASH. Choose a video and set the resolution. This may take a few times, but eventually the resolution that is selected is ignored until a refresh happens, which itself has a small chance of not fixing it.

**Expected behavior**
Resolution should be set to the requested resolution.

**Comment by WardPearce** [comment]
Appears to be a upstream issue with https://github.com/vidstack/player

**Comment by Spaghetto392** [comment]
If so, I would ask you file an issue with them, as I have no familiarity with Vidstack or their ecosystem, and will probably be of little help to them.
