### ISSUE TITLE
Add path for Youtube thumbnails

### ISSUE THREAD

**Issue by Spaghetto392** [Materialious/Materialious#698]
**Describe the bug**
If a user uses an extension such as Libredirect, and tries to view a thumbnail from Youtube (such as a image search result) the user will be redirected to a 404 page upon visiting the link.

**To Reproduce**
Example: https://{INSTANCE_NAME}/vi/pbrGuiCh_ug/maxresdefault.jpg

**Expected behavior**
The link should return the thumbnail image file from Youtube.

**Comment by WardPearce** [comment]
Such path is out of scope for Materialious.

**Comment by Spaghetto392** [comment]
@WardPearce In that case, I would recommend setting up a redirect to the Invidious' instance's handling of thumbnails.

https://yewtu.be/vi/pbrGuiCh_ug/maxresdefault.jpg
