### ISSUE TITLE
Split APKs?

### ISSUE THREAD

**Issue by IzzySoft** [Materialious/Materialious#712]
With v1.5.0, the size of the APK files "exploded" by factor 4+ (from 15 MB to 66 MB). Would it be possible to provide per-ABI splits? That would bring each APK down to between 30 and 40 MB (as each ABI holds more than 15 MB compressed native libs).

Thanks for considering!

**Comment by WardPearce** [comment]
Our CI pipelines are currently being changed, so will deffo look into this!

**Comment by IzzySoft** [comment]
Unfortunately, we're back at 60 MB now for the arm64 build. 50 MB are native libraries, which are stored into the APK uncompressed. Would you consider enabling legacyCompression? That would bring them down by ~25 MB, and thus the APK size at least closer to the 30 MB per-app size limit we have at IzzyOnDroid, @WardPearce 🙏
