### ISSUE TITLE
Videos missing from subscriptions section on main instance

### ISSUE THREAD

**Issue by ArjhanToteck** [Materialious/Materialious#713]
**Describe the bug**
In the subscriptions section there are often videos missing.

**To Reproduce**
Subscribe to a lot of channels, eventually some videos will not show up in the subscription feed.

**Expected behavior**
All videos from subscribed channels showing in subscriptions feed.

**Additional context**
This is likely an Invidious config issue. They recommend enabling PubSub and restarting the server every hour or at least once per day, if that is not already done:

https://github.com/iv-org/invidious/issues/3395

https://docs.invidious.io/installation/#post-install-configuration

**Comment by WardPearce** [comment]
Greetings, thanks for your issue & I've noticed this too. Our instance does use PubSub, restarts hourly & runs on multiple threads. Recently a upstream Invidious issue was causing sub feed not to update, but has been resolved now.

Possibly is a different upstream issue? Not sure

**Comment by WardPearce** [comment]
Possibly a issue with too many subscriptions.
